- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ansibleRG
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3U76mfMN/htPFnZZV50KaISTWUNwu0f3yuaZLlK8zMXuKAjDKZPjuXV5jrTgGN5YZ2I8m0H1HhU1a89O6UhfiV7i+BWSw8ypQK9ePZIQp8UDZQ/cXaS+mN+50rnJq37ruv8HUOTzZUTil/q8523PELDpKF7EhrSJT+DcUNE0KWIexdJv2fIBe9Db0isN/UYss/mAitiPcEGym84IWjDoyMEFOigSSCEtCcLtHzpmMStNPQSM9l2dzsyZGYnwaHtV0lKoKBC1hYsXzgoCq8Q8KU27QUwJ1JI7m521UF6hPLHKoZjFkD8O9IMRKa0p3EpOGu19v7RiYjUADupF9nXct"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
